baseURL = "http://susananastacio.netlify.com"
languageCode = "en-us"
title = "Susana Anast√°cio"
relativeURLs = true
pluralizelisttitles = false
summaryLength = 60



[permalinks]
  post = "/:month/:year/:title/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 2

[[menu.main]]
  name = "Viagens"
  url = "/viagens"
  weight = 3


[[menu.main]]
  name = "Projectos"
  url = "/projectos"
  weight = 4


[[menu.main]]
  name = "Contactos"
  url = "/contactos"
  weight = 5
